"""create challenge

Revision ID: 1072da7fffeb
Revises: 19c5f1a3cb88
Create Date: 2021-09-21 12:17:04.902127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1072da7fffeb"
down_revision = "19c5f1a3cb88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Challenge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statement", sa.String(length=1000), nullable=False),
        sa.Column("answer", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Challenge")
    # ### end Alembic commands ###
