"""rename attempt

Revision ID: 19c5f1a3cb88
Revises: e48d7389a9c2
Create Date: 2021-09-21 08:24:49.486321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19c5f1a3cb88"
down_revision = "e48d7389a9c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("Attempt", "ProblemAttempt")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("ProblemAttempt", "Attempt")
    # ### end Alembic commands ###
