"""add house

Revision ID: 44d6f04e1a8f
Revises: a28bc267e90b
Create Date: 2021-10-12 09:01:19.783735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44d6f04e1a8f"
down_revision = "a28bc267e90b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column(
            "house",
            sa.Enum(
                "thomas",
                "davidson",
                "perry ross",
                "cromwell",
                "cleve",
                "griswold",
                "woodhull",
                "dickinson",
                "kennedy",
                "hamill",
                "kirby",
                "carter",
                "stephens",
                "stanley",
                "mcClellan",
                "upper",
                "reynolds",
                "mcPherson",
                "kinnan",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "house")
    # ### end Alembic commands ###
