"""create challenge attempt

Revision ID: a28bc267e90b
Revises: 1072da7fffeb
Create Date: 2021-09-21 12:23:53.993935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a28bc267e90b"
down_revision = "1072da7fffeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ChallengeAttempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["Challenge.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ChallengeAttempt")
    # ### end Alembic commands ###
